import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const passiveTreeHtml = readFileSync(new URL("../public/passive_tree.html", import.meta.url), "utf8");

test("passive tree inline script parses after loading data", () => {
  const inlineScript = passiveTreeHtml.match(/<script>\s*([\s\S]*?)\s*<\/script>\s*<\/body>/)?.[1] || "";

  assert.ok(inlineScript);
  assert.doesNotThrow(() => new Function(inlineScript));
  assert.match(passiveTreeHtml, /<script src="data\/passive-tree-data\.js\?v=20260525-passive-audit-render-fix"><\/script>\s*<script>\s*const initPassiveTree = \(\) =>/);
  assert.doesNotMatch(passiveTreeHtml, /document\.createElement\("script"\)/);
  assert.doesNotMatch(passiveTreeHtml, /script\.onload = initPassiveTree/);
  assert.match(passiveTreeHtml, /showPassiveTreeBootError/);
  assert.match(passiveTreeHtml, /try \{\s+initPassiveTree\(\);\s+\} catch \(error\) \{/);
});

test("passive tree map exposes zoom, pan, fit, and hover tooltip interactions", () => {
  assert.match(passiveTreeHtml, /id="treeMapViewport"/);
  assert.match(passiveTreeHtml, /id="treeMapTooltip"/);
  assert.match(passiveTreeHtml, /data-map-zoom="in"/);
  assert.match(passiveTreeHtml, /data-map-zoom="out"/);
  assert.match(passiveTreeHtml, /id="fitTreeMap"/);
  assert.match(passiveTreeHtml, /id="resetTreeMap"/);
  assert.match(passiveTreeHtml, /id="copyPassiveBuild"/);
  assert.match(passiveTreeHtml, /id="importPassiveBuild"/);
  assert.match(passiveTreeHtml, /id="togglePassiveSummary"/);
  assert.match(passiveTreeHtml, /id="expandTreeMap"/);
  assert.match(passiveTreeHtml, /id="collapseTreeMap"/);
  assert.match(passiveTreeHtml, /class="[^"]*\bpassive-tree-frame\b[^"]*" id="treeMapViewport"/);
  assert.match(passiveTreeHtml, /id="passiveBuildSummary"/);
  assert.match(passiveTreeHtml, /id="passiveSummaryNodes"/);
  assert.match(passiveTreeHtml, /components\/app-shell\.js\?v=20260525-tooltip-pin/);
  assert.match(passiveTreeHtml, /components\/passive-tree-planner\.js/);
  assert.match(passiveTreeHtml, /PoePassiveTreePlanner/);
  assert.match(passiveTreeHtml, /encodePassiveBuildState/);
  assert.match(passiveTreeHtml, /decodePassiveBuildState/);
  assert.match(passiveTreeHtml, /allocatedBuildNodeIds/);
  assert.match(passiveTreeHtml, /buildPassiveShareUrl/);
  assert.match(passiveTreeHtml, /passiveTreeBackgroundRadius/);
  assert.match(passiveTreeHtml, /passiveTreeConnectorGeometry/);
  assert.match(passiveTreeHtml, /projectAscendancyMapPointToClassDisc/);
  assert.match(passiveTreeHtml, /shouldDrawTreeConnection/);
  assert.match(passiveTreeHtml, /shouldShowPassiveTreeNode/);
  assert.match(passiveTreeHtml, /summarizeAllocatedNodes/);
  assert.match(passiveTreeHtml, /refundAllocatedNodeIds/);
  assert.match(passiveTreeHtml, /applyPassiveBuildState/);
  assert.match(passiveTreeHtml, /renderPassiveBuildSummary/);
  assert.match(passiveTreeHtml, /parsePassiveBuildInput/);
  assert.match(passiveTreeHtml, /id="classFilter"/);
  assert.match(passiveTreeHtml, /passive-map-toolbar/);
  assert.match(passiveTreeHtml, /drawConnectionPath/);
  assert.match(passiveTreeHtml, /drawFlatPassiveNode/);
  assert.match(passiveTreeHtml, /passiveIconForNode/);
  assert.match(passiveTreeHtml, /drawPassiveIcon/);
  assert.match(passiveTreeHtml, /shouldDrawPassiveIcon/);
  assert.match(passiveTreeHtml, /const HIGHLIGHT_ICON_DETAIL_MIN = \.12/);
  assert.match(passiveTreeHtml, /const IMPORTANT_ICON_DETAIL_MIN = \.18/);
  assert.match(passiveTreeHtml, /const SMALL_ICON_DETAIL_MIN = \.26/);
  assert.match(passiveTreeHtml, /const SMALL_ICON_RADIUS_MIN = 1\.75/);
  assert.match(passiveTreeHtml, /if \(highlighted && detail >= HIGHLIGHT_ICON_DETAIL_MIN\) return true;/);
  assert.match(passiveTreeHtml, /return detail >= SMALL_ICON_DETAIL_MIN;/);
  assert.match(passiveTreeHtml, /return detail >= IMPORTANT_ICON_DETAIL_MIN;/);
  assert.match(passiveTreeHtml, /radius >= SMALL_ICON_RADIUS_MIN && drawPassiveIcon/);
  assert.match(passiveTreeHtml, /drawPathHighlights/);
  assert.match(passiveTreeHtml, /drawSearchHighlights/);
  assert.match(passiveTreeHtml, /computePathToNode/);
  assert.match(passiveTreeHtml, /allocatePathToNode/);
  assert.match(passiveTreeHtml, /const ALLOCATED_PATH_COLOR = "#f8d76a"/);
  assert.match(passiveTreeHtml, /const HOVER_PATH_COLOR = "#22ff8a"/);
  assert.match(passiveTreeHtml, /const HOVER_PICK_MAX_PIXELS = 52/);
  assert.match(passiveTreeHtml, /const CLICK_PICK_MAX_PIXELS = 52/);
  assert.doesNotMatch(passiveTreeHtml, /const CLICK_PICK_MAX_PIXELS = Infinity/);
  assert.match(passiveTreeHtml, /for \(const key of path\.edgeKeys\) allocatedEdgeKeys\.add\(key\);\s+hoverPathNodeIds = new Set\(\);\s+hoverPathEdgeKeys = new Set\(\);\s+hoverPathPointGain = 0;/);
  assert.match(passiveTreeHtml, /deallocatePathFromNode/);
  assert.match(passiveTreeHtml, /togglePathAllocation/);
  assert.match(passiveTreeHtml, /syncSpecStartNodes/);
  assert.match(passiveTreeHtml, /specStartNodeIds/);
  assert.match(passiveTreeHtml, /selectedClassMeta/);
  assert.match(passiveTreeHtml, /defaultClassValue/);
  assert.match(passiveTreeHtml, /firstAscendancyValueForClass/);
  assert.match(passiveTreeHtml, /const ascendancyRows = classRows\.flatMap/);
  assert.doesNotMatch(passiveTreeHtml, /ascendancyRows = \[\.\.\.new Set\(nodes\.map\(\(node\) => node\.ascendancy_name\)/);
  assert.match(passiveTreeHtml, /updateAscendancyOptionsForClass/);
  assert.match(passiveTreeHtml, /classOptionRows = \(rows\) => rows\.map/);
  assert.match(passiveTreeHtml, /ascFilter\.value = firstAscendancyValueForClass\(className\);/);
  assert.match(passiveTreeHtml, /currentSearchMatchIds/);
  assert.match(passiveTreeHtml, /selectedAscendancyMeta/);
  assert.match(passiveTreeHtml, /projectClassStartNodesToClassDisc/);
  assert.match(passiveTreeHtml, /let classGateEdges =/);
  assert.match(passiveTreeHtml, /let renderTreeEdges =/);
  assert.match(passiveTreeHtml, /fitBoxForSelectedAscendancy/);
  assert.match(passiveTreeHtml, /drawTreeArtBackgrounds/);
  assert.match(passiveTreeHtml, /node\.ascendancy_name === ascFilter\.value/);
  assert.match(passiveTreeHtml, /classFilter\.value !== "all"/);
  assert.match(passiveTreeHtml, /className: selectedClassName\(\)/);
  assert.match(passiveTreeHtml, /node\.is_class_start/);
  assert.match(passiveTreeHtml, /const CLASS_DISC_RADIUS_SCALE = \.91/);
  assert.match(passiveTreeHtml, /radiusScale: CLASS_DISC_RADIUS_SCALE/);
  assert.doesNotMatch(passiveTreeHtml, /createRadialGradient/);
  assert.doesNotMatch(passiveTreeHtml, /treeMapContext\.fill\(\);\s+treeMapContext\.globalAlpha = strokeAlpha;/);
  assert.doesNotMatch(passiveTreeHtml, /const ASCENDANCY_HUB_RADIUS = /);
  assert.doesNotMatch(passiveTreeHtml, /ASCENDANCY_TREE_RADIUS/);
  assert.doesNotMatch(passiveTreeHtml, /ASCENDANCY_CIRCLE_RADIUS/);
  assert.doesNotMatch(passiveTreeHtml, /render_in_hub/);
  assert.doesNotMatch(passiveTreeHtml, /ascendancyHubAtMapEvent/);
  assert.doesNotMatch(passiveTreeHtml, /openAscendancyFromHub/);
  assert.doesNotMatch(passiveTreeHtml, /ascendancyOptionRows = \(rows\) => `[^`]*value="all"/s);
  assert.doesNotMatch(passiveTreeHtml, /for \(const ascendancy of ascendancies\)/);
  assert.match(passiveTreeHtml, /id="passivePointCount"/);
  assert.match(passiveTreeHtml, /id="ascPointCount"/);
  assert.match(passiveTreeHtml, /id="passiveSummaryPointTotals"/);
  assert.match(passiveTreeHtml, /id="passiveSummarySections"/);
  assert.match(passiveTreeHtml, /const passiveStatCategory = /);
  assert.match(passiveTreeHtml, /const allocatedPassiveStatGroups = /);
  assert.match(passiveTreeHtml, /class="passive-stat-group/);
  assert.match(passiveTreeHtml, /Passive: <span id="passiveSummaryPassiveCount">0<\/span>/);
  assert.doesNotMatch(passiveTreeHtml, /passive-tree-icon-atlas\.js/);
  assert.doesNotMatch(passiveTreeHtml, /drawGroupArt/);
  assert.doesNotMatch(passiveTreeHtml, /drawFramedPassiveNode/);
  assert.match(passiveTreeHtml, /const mapView = \{/);
  assert.match(passiveTreeHtml, /const setMapExpanded = \(expanded\) => \{/);
  assert.match(passiveTreeHtml, /document\.body\.classList\.toggle\("passive-map-expanded", expanded\);/);
  assert.match(passiveTreeHtml, /expandTreeMap\.addEventListener\("click", \(\) => setMapExpanded\(true\)\);/);
  assert.match(passiveTreeHtml, /collapseTreeMap\.addEventListener\("click", \(\) => setMapExpanded\(false\)\);/);
  assert.match(passiveTreeHtml, /const fitMapToNodes = \(/);
  assert.match(passiveTreeHtml, /const zoomMapAt = \(/);
  assert.match(passiveTreeHtml, /treeMapViewport\.addEventListener\("wheel"/);
  assert.match(passiveTreeHtml, /treeMapViewport\.addEventListener\("pointerdown"/);
  assert.match(passiveTreeHtml, /treeMapViewport\.addEventListener\("pointermove"/);
  assert.match(passiveTreeHtml, /treeMapViewport\.addEventListener\("pointerleave"/);
  assert.match(passiveTreeHtml, /treeMapViewport\.addEventListener\("dblclick"/);
  assert.match(passiveTreeHtml, /<canvas class="block" id="treeMap"/);
  assert.match(passiveTreeHtml, /getContext\("2d"/);
  assert.match(passiveTreeHtml, /const requestMapDraw = /);
  assert.match(passiveTreeHtml, /window\.requestAnimationFrame/);
  assert.match(passiveTreeHtml, /const MAX_DRAWABLE_EDGE_LENGTH = /);
  assert.match(passiveTreeHtml, /const NODE_INDEX_CELL_SIZE = /);
  assert.match(passiveTreeHtml, /const EDGE_INDEX_CELL_SIZE = /);
  assert.match(passiveTreeHtml, /const MAP_VIEW_OVERSCROLL_RATIO = /);
  assert.match(passiveTreeHtml, /const pathEdges = data\.path_edges \|\| edges/);
  assert.match(passiveTreeHtml, /const rebuildMapNodeIndex = /);
  assert.match(passiveTreeHtml, /const rebuildMapEdgeIndex = /);
  assert.match(passiveTreeHtml, /const visibleMapEdgesForViewport = /);
  assert.match(passiveTreeHtml, /const drawableEdges = /);
  assert.match(passiveTreeHtml, /const nodeAtMapEvent = /);
  assert.match(passiveTreeHtml, /const nearestNodeAtMapEvent = /);
  assert.match(passiveTreeHtml, /const nearestNodeAtMapEvent = \(event, maxPixels = CLICK_PICK_MAX_PIXELS\) => nodeAtMapEvent\(event, maxPixels\);/);
  assert.doesNotMatch(passiveTreeHtml, /const candidates = Number\.isFinite\(maxPixels\) \? nearbyIndexedNodes\(point, maxDistance\) : mapInteractionNodes/);
  assert.match(passiveTreeHtml, /treeMapViewport\.addEventListener\("click", \(event\) => \{\s+if \(suppressNextMapClick\) return;\s+const node = nearestNodeAtMapEvent\(event\);/);
  assert.doesNotMatch(passiveTreeHtml, /treeMap\.addEventListener\("click"/);
  assert.match(passiveTreeHtml, /allocatedNodeIds = refundAllocatedNodeIds\(\{/);
  assert.doesNotMatch(passiveTreeHtml, /if \(selectedNodeId\) window\.setTimeout\(\(\) => openNodeModal\(selectedNodeId\), 150\);/);
  assert.doesNotMatch(passiveTreeHtml, /ignoreDistanceLimit/);
  assert.doesNotMatch(passiveTreeHtml, /maxDistance: ignoreDistanceLimit \? Infinity/);
  assert.match(passiveTreeHtml, /showMapTooltip/);
  assert.match(passiveTreeHtml, /hideMapTooltip/);
  assert.match(passiveTreeHtml, /scheduleHideMapTooltip/);
  assert.match(passiveTreeHtml, /\.map-tooltip \{[^}]*left: 0;[^}]*top: 0;/s);
  assert.match(passiveTreeHtml, /let left = event\.clientX \+ 18;/);
  assert.match(passiveTreeHtml, /left = event\.clientX - width \/ 2;/);
  assert.match(passiveTreeHtml, /moveMapTooltip\(event\);/);
  assert.match(passiveTreeHtml, /<div class="passive-tooltip-main">/);
  assert.match(passiveTreeHtml, /<div class="passive-tooltip-title" translate="no">/);
  assert.match(passiveTreeHtml, /<div class="passive-tooltip-stats">/);
  assert.match(passiveTreeHtml, /<div class="passive-tooltip-footer">/);
  assert.match(passiveTreeHtml, /let mapTooltipPinned = false;/);
  assert.match(passiveTreeHtml, /let mapTooltipPointerInside = false;/);
  assert.match(passiveTreeHtml, /const setMapTooltipPinned = \(pinned\) =>/);
  assert.match(passiveTreeHtml, /\.map-tooltip\.is-pinned \{[^}]*pointer-events: auto;/s);
  assert.match(passiveTreeHtml, /event\.altKey\) setMapTooltipPinned\(true\);/);
  assert.match(passiveTreeHtml, /window\.PoeAppShell\?\.applyTooltips\?\.\(treeMapTooltip\);/);
  assert.match(passiveTreeHtml, /treeMapTooltip\.addEventListener\("mouseenter"/);
  assert.match(passiveTreeHtml, /treeMapTooltip\.addEventListener\("mouseleave"/);
  assert.match(passiveTreeHtml, /event\.key === "Alt"/);
  assert.match(passiveTreeHtml, /if \(mapTooltipPinned \|\| mapTooltipPointerInside\) return;/);
  assert.match(passiveTreeHtml, /passive-tooltip-hint/);
  assert.match(passiveTreeHtml, /passive-map-toolbar, \.map-control, \.map-tooltip,/);
  assert.doesNotMatch(passiveTreeHtml, /inline-flex rounded-full border border-emerald-300\/30/);
  assert.doesNotMatch(passiveTreeHtml, /syncMapNodeScale/);
  assert.doesNotMatch(passiveTreeHtml, /treeMap\.innerHTML/);
});

test("passive tree scopes canvas view with soft bounds and culls edge drawing", () => {
  assert.match(passiveTreeHtml, /clampPassiveMapView/);
  assert.match(passiveTreeHtml, /buildPassiveRectSpatialIndex/);
  assert.match(passiveTreeHtml, /queryPassiveRectSpatialIndex/);
  assert.match(passiveTreeHtml, /const mapViewBoundsOptions = /);
  assert.match(passiveTreeHtml, /const clampMapViewToSoftBounds = \(box\) =>/);
  assert.match(passiveTreeHtml, /setMapView\(box, \{ clampToBounds = true \} = \{\}\)/);
  assert.match(passiveTreeHtml, /clampToBounds \? clampMapViewToSoftBounds\(box\) : box/);
  assert.match(passiveTreeHtml, /const edgeBoundsForIndex = \(edge\) =>/);
  assert.match(passiveTreeHtml, /rebuildMapEdgeIndex\(mapContentEdges\);/);
  assert.match(passiveTreeHtml, /const visibleEdges = visibleMapEdgesForViewport\(viewport\);\s+drawTreeArtBackgrounds\(viewport\);\s+drawEdges\(viewport, visibleEdges\);/);
  assert.match(passiveTreeHtml, /const strokeEdges = \(viewport, visibleEdges, \{ color, width, alpha \}\) =>/);
  assert.match(passiveTreeHtml, /document\.visibilityState === "hidden"/);
});

test("passive tree page keeps the map in an expandable framed surface", () => {
  const clearSearchButtonCount = passiveTreeHtml.match(/id="clearPassiveSearch"/g)?.length || 0;

  assert.match(passiveTreeHtml, /passive-tree-body/);
  assert.match(passiveTreeHtml, /<body class="[^"]*\boverflow-hidden\b/);
  assert.match(passiveTreeHtml, /\.passive-tree-body \{[^}]*height: 100dvh;[^}]*display: flex;[^}]*flex-direction: column;[^}]*overflow-y: hidden;/s);
  assert.match(passiveTreeHtml, /body\.passive-map-expanded \{[^}]*overflow: hidden;/s);
  assert.match(passiveTreeHtml, /data-component="site-header"/);
  assert.match(passiveTreeHtml, /<main class="[^"]*\bpassive-tree-page\b[^"]*\bp-0\b/);
  assert.match(passiveTreeHtml, /--passive-header-height: 65px;/);
  assert.match(passiveTreeHtml, /const syncPassiveHeaderHeight = \(\) =>/);
  assert.match(passiveTreeHtml, /document\.documentElement\.style\.setProperty\("--passive-header-height", `\$\{height\}px`\);/);
  assert.match(passiveTreeHtml, /\.passive-tree-page \{[^}]*flex: 1 1 auto;[^}]*min-height: 0;[^}]*height: auto;/s);
  assert.match(passiveTreeHtml, /\.passive-panel \{[^}]*height: 100%;[^}]*padding: 0;/s);
  assert.match(passiveTreeHtml, /\.passive-tree-frame \{[^}]*height: 100%;[^}]*min-height: 0;/s);
  assert.doesNotMatch(passiveTreeHtml, /height: min\(72dvh, 820px\);/);
  assert.doesNotMatch(passiveTreeHtml, /padding: clamp\(12px, 2\.4vw, 24px\);/);
  assert.match(passiveTreeHtml, /body\.passive-map-expanded \.passive-tree-frame \{[^}]*position: fixed;[^}]*inset: 0;[^}]*width: 100vw;[^}]*height: 100dvh;/s);
  assert.doesNotMatch(passiveTreeHtml, /body\.passive-map-expanded \.passive-tree-frame \{[^}]*inset: var\(--passive-header-height\) 0 0;/s);
  assert.doesNotMatch(passiveTreeHtml, /<div class="[^"]*\bh-dvh\b[^"]*" id="treeMapViewport"/);
  assert.doesNotMatch(passiveTreeHtml, /<h1[^>]*>Passive tree<\/h1>/);
  assert.match(passiveTreeHtml, /id="treeVersion"[^>]*>Đang tải dữ liệu\./);
  assert.match(passiveTreeHtml, /id="resultMeta"[^>]*>Đang tải dữ liệu\./);
  assert.equal(clearSearchButtonCount, 1);
  assert.match(passiveTreeHtml, /id="resultMeta"[^>]*>[^<]*<\/p>\s*<canvas class="block" id="treeMap"/);
  assert.doesNotMatch(passiveTreeHtml, /id="nodeGrid"/);
  assert.doesNotMatch(passiveTreeHtml, /id="loadMoreNodes"/);
  assert.doesNotMatch(passiveTreeHtml, /renderNodeCard/);
  assert.doesNotMatch(passiveTreeHtml, /renderGrid/);
});

test("passive tree search highlights matches without hiding the rest of the tree", () => {
  assert.match(passiveTreeHtml, /id="passiveSearchResults"/);
  assert.match(passiveTreeHtml, /id="passiveSearchSections"/);
  assert.match(passiveTreeHtml, /let currentSearchTerms = \[\];/);
  assert.match(passiveTreeHtml, /const parseSearchTerms = /);
  assert.match(passiveTreeHtml, /const searchDimmedNode = /);
  assert.match(passiveTreeHtml, /const renderPassiveSearchResults = /);
  assert.match(passiveTreeHtml, /const searchMatches = currentSearchTerms\.length\s+\? filtered\.filter\(\(node\) => nodeSearchMatches\(node, currentSearchTerms\)\)/);
  assert.match(passiveTreeHtml, /currentSearchMatchIds = new Set\(searchMatches\.map\(\(node\) => String\(node\.id\)\)\);/);
  assert.match(passiveTreeHtml, /const visibleNodes = visibleMapNodesForViewport\(viewport\);\s+const visibleEdges = visibleMapEdgesForViewport\(viewport\);\s+drawTreeArtBackgrounds\(viewport\);\s+drawEdges\(viewport, visibleEdges\);\s+drawPathHighlights\(viewport\);\s+drawSearchHighlights\(viewport, visibleNodes\);\s+drawNodes\(viewport, visibleNodes\);/);
  assert.match(passiveTreeHtml, /passiveSearchSections\.addEventListener\("click"/);
  assert.doesNotMatch(passiveTreeHtml, /queryMatches: nodeSearchMatches\(node, query\)/);
});

test("passive tree anchors search results directly below the search input", () => {
  const filterbar = passiveTreeHtml.match(/<div class="passive-map-toolbar passive-map-filterbar[\s\S]*?<p class="sr-only" id="treeVersion"/)?.[0] || "";
  const searchWrap = filterbar.match(/<div class="passive-search-wrap[\s\S]*?<\/aside>\s*<\/div>/)?.[0] || "";

  assert.match(searchWrap, /id="searchInput"/);
  assert.match(searchWrap, /id="passiveSearchResults"/);
  assert.ok(searchWrap.indexOf('id="searchInput"') < searchWrap.indexOf('id="passiveSearchResults"'));
  assert.match(passiveTreeHtml, /\.passive-search-wrap \{[^}]*position: relative;/s);
  assert.match(passiveTreeHtml, /\.passive-search-results \{[^}]*left: 0;[^}]*right: 0;[^}]*top: calc\(100% \+ \.5rem\);/s);
  assert.doesNotMatch(passiveTreeHtml, /<p class="sr-only" id="resultMeta">[\s\S]*?<aside class="passive-search-results/);
});

test("passive tree selected summary cards keep dark-mode colors without generated utility classes", () => {
  assert.match(passiveTreeHtml, /\.passive-summary-card \{[^}]*background: rgba\(248, 250, 252, \.92\);/s);
  assert.match(passiveTreeHtml, /\.dark \.passive-summary-card \{[^}]*background: rgba\(15, 23, 42, \.82\);/s);
  assert.match(passiveTreeHtml, /\.passive-summary-card-title \{[^}]*color: #0f172a;/s);
  assert.match(passiveTreeHtml, /\.dark \.passive-summary-card-title \{[^}]*color: #f8fafc;/s);
  assert.match(passiveTreeHtml, /\.passive-summary-node \{[^}]*background: rgba\(248, 250, 252, \.92\);/s);
  assert.match(passiveTreeHtml, /\.dark \.passive-summary-node \{[^}]*background: rgba\(15, 23, 42, \.82\);/s);
  assert.match(passiveTreeHtml, /class="passive-stat-group passive-summary-card/);
  assert.match(passiveTreeHtml, /class="passive-summary-node/);
});

test("passive tree supports light and dark theme for page chrome and canvas drawing", () => {
  assert.match(passiveTreeHtml, /<body class="[^"]*\bbg-slate-50\b[^"]*\btext-slate-950\b[^"]*\bdark:bg-slate-950\b/);
  assert.match(passiveTreeHtml, /\.passive-tree-page \{[^}]*background: #eef2f7;/s);
  assert.match(passiveTreeHtml, /\.dark \.passive-tree-page \{[^}]*background: #020611;/s);
  assert.match(passiveTreeHtml, /#treeMapViewport \{[^}]*background: #eef2f7;/s);
  assert.match(passiveTreeHtml, /\.dark #treeMapViewport \{[^}]*background: #020611;/s);
  assert.match(passiveTreeHtml, /const passiveTreeLightPalette = \{/);
  assert.match(passiveTreeHtml, /const passiveTreeDarkPalette = \{/);
  assert.match(passiveTreeHtml, /const isPassiveTreeDarkTheme = \(\) => document\.documentElement\.classList\.contains\("dark"\);/);
  assert.match(passiveTreeHtml, /const passiveTreeTheme = \(\) => isPassiveTreeDarkTheme\(\) \? passiveTreeDarkPalette : passiveTreeLightPalette;/);
  assert.match(passiveTreeHtml, /const palette = passiveTreeTheme\(\);[\s\S]*treeMapContext\.fillStyle = palette\.background;/);
  assert.match(passiveTreeHtml, /strokeEdges\(viewport, visibleEdges, \{[\s\S]*color: palette\.edgeShadow,/);
  assert.match(passiveTreeHtml, /window\.addEventListener\("poe-theme-change", \(\) => requestMapDraw\(\)\);/);
});
